BlueBrain/nexus-iam

- modules/service/src/main/resources/app.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/AppConfig.scala
- modules/service/src/test/resources/test-settings.conf
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/config/PureConfigSpec.scala
> Configured service to join the cluster with provided seeds

- .gitignore
- modules/service/src/main/resources/kamon.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/StaticRoutes.scala
Added trace name for the service description route.
> Updated monitoring to describe its environment

- build.sbt
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/auth/DownstreamAuthClient.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/auth/DownstreamAuthClientSpec.scala
- modules/service/src/main/resources/app.conf
- modules/service/src/main/resources/application.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/AppConfig.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/Settings.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/CommonRejections.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/RejectionHandling.scala
- modules/service/src/test/resources/test-settings.conf
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
> Forward authentication calls to downstream provider

- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/auth/DownstreamAuthClient.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/auth/DownstreamAuthClientSpec.scala
> Fix bug in mapping responses from OIDC provider

- modules/oidc/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/oidc/routes/AuthRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
> Add tracing to IAM routes.

- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/auth/UserInfo.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClientSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
> Fix user info decoding and add test

- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClientSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
> Fix userinfo error forwarding

- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Permissions.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/AuthenticationFailure.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/ExceptionHandling.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/RejectionHandling.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClientSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
Also, I modified the route so that getting your own ACLs works with any of (read, write, own) permissions.
> Refactor and fix user info error handling

- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Acls.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/CallerCtx.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/acls/AclsSpec.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
> Stored real identity of the caller instead of Anonymous

- modules/service/src/main/resources/app.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/AppConfig.scala
- modules/service/src/test/resources/test-settings.conf
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/config/PureConfigSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
- project/build.properties
> Test mode (give admin rights to Anonymous)

- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
- modules/service/src/test/resources/auth/user.json
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
> Fixed duplicated realms in the @id field

- docs/src/main/paradox/assets/api-reference/acl.json
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
> Added fix for duplicated realms on @id

- docs/src/main/paradox/api-reference/acls.md
- docs/src/main/paradox/assets/api-reference/acl-put.sh
- docs/src/main/paradox/assets/api-reference/error-example.json
- docs/src/main/paradox/internals/index.md
> Added docs for Integration Layer

- build.sbt
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/groups/GroupAlreadyAddedRejection.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/groups/GroupPermissionAddedCommand.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/groups/GroupPermissionAddedEvent.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/groups/UsedGroups.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/groups/UsedGroupsSpec.scala
- modules/service/src/main/resources/application.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/ClaimExtractor.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/groups/UsedGroupsAggregator.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/io/Serializer.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/auth/CredentialsStoreSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
> Allow filtering groups in user endpoint.

- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/queue/KafkaPublisher.scala
> Removed not needed realms path

- build.sbt
- docs/src/main/paradox/api-reference/acls.md
- docs/src/main/paradox/assets/api-reference/acl-post.sh
- docs/src/main/paradox/assets/api-reference/acl.json
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Acls.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Command.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/CommandRejection.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/acls/AclsSpec.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/groups/UsedGroupsAggregator.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/ExceptionHandling.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/io/SerializerSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/io/TaggingAdapterSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
> Merged AddPermissions and CreatePermissions

- docs/src/main/paradox/api-reference/acls.md
- docs/src/main/paradox/assets/api-reference/acl-patch-response.json
- docs/src/main/paradox/assets/api-reference/acl-patch.json
- docs/src/main/paradox/assets/api-reference/acl-patch.sh
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/Acls.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/CommandRejection.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/acls/AclsSpec.scala
- modules/service/src/main/resources/patch/subtract_1.json
- modules/service/src/main/resources/patch/subtract_2.json
- modules/service/src/main/resources/patch/subtract_3.json
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/ExceptionHandling.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/types/PartialUpdate.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/types/PartialUpdateSpec.scala
> Added API endpoint to subtract permissions from a resource

- build.sbt
- modules/service/src/main/resources/app.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/AppConfig.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/Settings.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/DefaultRoutes.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/ExceptionHandling.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/RejectionHandling.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/types/PartialUpdate.scala
- modules/service/src/test/resources/auth/user.json
- modules/service/src/test/resources/test-settings.conf
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/config/PureConfigSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/Error.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/types/PartialUpdateSpec.scala
> Add context to IAM responses

- build.sbt
- docs/src/main/paradox/api-reference/acls.md
- docs/src/main/paradox/assets/api-reference/acl-get-depth-all.sh
- docs/src/main/paradox/assets/api-reference/acl-get-depth.sh
- docs/src/main/paradox/assets/api-reference/acl-get-parents.sh
- docs/src/main/paradox/assets/api-reference/acl-get-self-parents.sh
- docs/src/main/paradox/assets/api-reference/acl-get-self.sh
- docs/src/main/paradox/assets/api-reference/acl-get.sh
- docs/src/main/paradox/assets/api-reference/full-acls-parents.json
- docs/src/main/paradox/assets/api-reference/full-acls-self-parents.json
- docs/src/main/paradox/assets/api-reference/full-acls-self.json
- docs/src/main/paradox/assets/api-reference/full-acls.json
- modules/elastic/src/main/scala/ch/epfl/bluebrain/nexus/iam/elastic/AclIndexer.scala
- modules/elastic/src/main/scala/ch/epfl/bluebrain/nexus/iam/elastic/ElasticConfig.scala
- modules/elastic/src/main/scala/ch/epfl/bluebrain/nexus/iam/elastic/ElasticIds.scala
- modules/elastic/src/main/scala/ch/epfl/bluebrain/nexus/iam/elastic/query/FilterAcls.scala
- modules/elastic/src/test/scala/ch/epfl/bluebrain/nexus/iam/elastic/FilterAclsSpec.scala
- modules/service/src/main/resources/identities-acls-simple.json
- modules/service/src/main/resources/identities-acls.json
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
Added also the support for the query parameters `self` and `parents`.
Fixes #80
> Listed ACLs for users, with address wildcard support

- build.sbt
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/User.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/CallerCtx.scala
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/types/UserInfo.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/acls/AclsSpec.scala
- modules/core/src/test/scala/ch/epfl/bluebrain/nexus/iam/core/types/UserInfoSpec.scala
- modules/elastic/src/main/scala/ch/epfl/bluebrain/nexus/iam/elastic/query/FilterAcls.scala
- modules/elastic/src/test/scala/ch/epfl/bluebrain/nexus/iam/elastic/AclIndexerSpec.scala
- modules/elastic/src/test/scala/ch/epfl/bluebrain/nexus/iam/elastic/FilterAclsSpec.scala
- modules/service/src/main/resources/application.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/ClaimExtractor.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/groups/UserGroupsOps.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutes.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/auth/ClaimExtractorSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AclsRoutesSpec.scala
- modules/service/src/test/scala/ch/epfl/bluebrain/nexus/iam/service/routes/AuthRoutesSpec.scala
- project/build.properties
- project/plugins.sbt
> Bumped dependencies and changed akka logging environment variable

- build.sbt
- modules/oidc/bbp/src/main/scala/ch/epfl/bluebrain/nexus/iam/bbp/Main.scala
- modules/oidc/core/src/main/resources/app.conf
- modules/oidc/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/oidc/BootstrapService.scala
- modules/oidc/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/oidc/ExternalConfig.scala
- modules/oidc/hbp/src/main/scala/ch/epfl/bluebrain/nexus/iam/hbp/Main.scala
- modules/service/src/main/resources/app.conf
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/Main.scala
- modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/config/AppConfig.scala
The dependency inherits a configuration for the OperationNameGenerator implementation.
> Updated commons-kamon dependency

- build.sbt
- modules/core/src/main/scala/ch/epfl/bluebrain/nexus/iam/core/acls/State.scala
- project/plugins.sbt
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/AccessControlLists.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/AclCommand.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/AclEvent.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/AclRejection.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/AclState.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/Acls.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/package.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/config/AppConfig.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/config/Settings.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/directives/AclDirectives.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/index/AclsIndex.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/index/InMemoryAclsTree.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/marshallers/instances.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/routes/AclsRoutes.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/types/Identity.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/types/Permission.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/types/ResourceF.scala
- src/test/resources/acls/acls-routes.json
- src/test/resources/acls/acls.json
- src/test/scala/ch/epfl/bluebrain/nexus/iam/acls/AccessControlListsSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/acls/AclsRoutesSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/acls/AclsSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/index/InMemoryAclsTreeBenchmark.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/index/InMemoryAclsTreeSpec.scala
- Fixed routes when listing ACLs using `*`
> Changed from service Path to Iri.Path

- build.sbt
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/Acls.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/package.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/config/AppConfig.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/config/Settings.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/index/InMemoryAclsTree.scala
- src/test/resources/application.conf
- src/test/scala/ch/epfl/bluebrain/nexus/iam/acls/AclsSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/index/InMemoryAclsTreeBenchmark.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/index/InMemoryAclsTreeSpec.scala
> Added listings of initial ACLs

- src/main/scala/ch/epfl/bluebrain/nexus/iam/acls/Acls.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/acls/AclsSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/permissions/PermissionsSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/realms/RealmsSpec.scala
Fixes https://github.com/BlueBrain/nexus/issues/353
> Allow replacing deleted ACLs.

- src/main/scala/ch/epfl/bluebrain/nexus/iam/types/Permission.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/routes/PermissionsRoutesSpec.scala
Fixes https://github.com/BlueBrain/nexus/issues/359
> Fix bug where permissions are truncated

- src/main/resources/akka.conf
- src/test/resources/contexts/iam-context.json
- src/test/resources/test.conf
Fixes https://github.com/BlueBrain/nexus/issues/338
> Added IAM context

- src/main/scala/ch/epfl/bluebrain/nexus/iam/realms/RealmRejection.scala
- src/main/scala/ch/epfl/bluebrain/nexus/iam/realms/Realms.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/realms/RealmsSpec.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/realms/WellKnownSpec.scala
Fixes https://github.com/BlueBrain/nexus/issues/371
> Prevented from having several realms using the same openIdConfig

- Jenkinsfile
- build.sbt
- src/main/resources/akka.conf
- src/main/scala/ch/epfl/bluebrain/nexus/iam/directives/AclDirectives.scala
- src/test/scala/ch/epfl/bluebrain/nexus/iam/routes/AclsRoutesSpec.scala
Fixes https://github.com/BlueBrain/nexus/issues/692
> Omit trailing slash on ACL routes
